## Create random animations

Animated SVGs are saved to the folder data/animated_svgs

In [1]:
import os
os.chdir("..")

In [2]:
import pickle
import warnings
import pandas as pd
from src.animations.create_random_animations import create_random_animations, combine_dataframes, create_backend_mapping_df
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', 10)

C:\Users\sarah\Anaconda3\lib\site-packages\scipy\__init__.py:137: UserWarning: NumPy 1.16.5 or above is required for this version of SciPy (detected version 1.16.1)
  UserWarning)

### 1. Create Animations
Animations are not completely random. Probabilies of path labeling are considered.

##### Specify number of animations per logo

In [10]:
nb_animations = 5

##### Animation vectors are saved as dataframe in animate_logos/data/animated_svgs_dataframes
If split_df=true, animation vectors are saved to multiple dataframes (one dataframe per logo).  
If split_df=false, animation vectors are saved to one dataframe and returned.

If nb_animations very high, use split_df=true.

In [9]:
split_df = False

In [11]:
create_random_animations("data/svgs_preprocessed_expanded", nb_animations, split_df)

No probability given for path with animation ID 6 in logo logo_0. Probability is set to 0.2. single positional indexer is out-of-bounds

,file,animation_id,order_id,path_prob,begin_value,model_output,animated_animation_ids,animated_order_ids,backend_mapping
0,logo_0_animation_0,5,0,0.578947,2.00,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[5, 0, 4, 3, 1]","[0, 1, 3, 4, 5]","[1, 1, 0, 1, 1, 1, 0, 0]"
1,logo_0_animation_0,0,1,0.526316,1.00,"[0, 0, 0, 1, 0, 0, -1.0, -1.0, -1.0, -1.0, 0.8...","[5, 0, 4, 3, 1]","[0, 1, 3, 4, 5]","[1, 1, 0, 1, 1, 1, 0, 0]"
2,logo_0_animation_0,4,3,0.526316,1.50,"[0, 0, 1, 0, 0, 0, -1.0, -1.0, -1.0, 0.4205715...","[5, 0, 4, 3, 1]","[0, 1, 3, 4, 5]","[1, 1, 0, 1, 1, 1, 0, 0]"
3,logo_0_animation_0,3,4,0.684211,1.25,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[5, 0, 4, 3, 1]","[0, 1, 3, 4, 5]","[1, 1, 0, 1, 1, 1, 0, 0]"
4,logo_0_animation_0,1,5,0.526316,1.75,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[5, 0, 4, 3, 1]","[0, 1, 3, 4, 5]","[1, 1, 0, 1, 1, 1, 0, 0]"
...,...,...,...,...,...,...,...,...,...
241,logo_73_animation_4,1,2,1.000000,2.00,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.3960582426106...","[0, 6, 1, 7, 13, 8, 2]","[0, 1, 2, 3, 4, 5, 6]","[1, 1, 1, 1, 1, 1, 1, 0]"
242,logo_73_animation_4,7,3,1.000000,2.25,"[1, 0, 0, 0, 0, 0, 0.15497227080241027, 0.0665...","[0, 6, 1, 7, 13, 8, 2]","[0, 1, 2, 3, 4, 5, 6]","[1, 1, 1, 1, 1, 1, 1, 0]"
243,logo_73_animation_4,13,4,0.833333,2.50,"[0, 0, 1, 0, 0, 0, -1.0, -1.0, -1.0, 0.4015910...","[0, 6, 1, 7, 13, 8, 2]","[0, 1, 2, 3, 4, 5, 6]","[1, 1, 1, 1, 1, 1, 1, 0]"
244,logo_73_animation_4,8,5,0.916667,1.75,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.9179550430877...","[0, 6, 1, 7, 13, 8, 2]","[0, 1, 2, 3, 4, 5, 6]","[1, 1, 1, 1, 1, 1, 1, 0]"
245,logo_73_animation_4,2,6,0.916667,1.50,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[0, 6, 1, 7, 13, 8, 2]","[0, 1, 2, 3, 4, 5, 6]","[1, 1, 1, 1, 1, 1, 1, 0]"

### 2. Concatenat dataframes
This function concatenates all pkl files in a given folder. Please move or delete all pkl files that you don't want to concantenate.

In [44]:
df_combined = combine_dataframes("data/animated_svgs_dataframes")
df_combined.head(20)

,file,animation_id,order_id,path_prob,begin_value,model_output,animated_animation_ids,animated_order_ids,backend_mapping
0,logo_316_animation_0,4,1,0.2,1.00,"[0, 0, 0, 1, 0, 0, -1.0, -1.0, -1.0, -1.0, 0.8...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]"
1,logo_316_animation_0,24,6,0.6,1.25,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]"
2,logo_316_animation_0,23,7,0.2,1.50,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]"
3,logo_316_animation_1,4,1,0.2,1.00,"[1, 0, 0, 0, 0, 0, 0.13436424411240122, 0.8474...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]"
4,logo_316_animation_1,24,6,0.6,1.25,"[0, 0, 1, 0, 0, 0, -1.0, -1.0, -1.0, 0.7637746...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]"
...,...,...,...,...,...,...,...,...,...
15,logo_316_animation_4,24,6,0.2,1.75,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[1, 4, 2, 24, 23]","[0, 1, 4, 6, 7]","[1, 1, 0, 0, 1, 0, 1, 1]"
16,logo_316_animation_4,23,7,0.2,2.00,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[1, 4, 2, 24, 23]","[0, 1, 4, 6, 7]","[1, 1, 0, 0, 1, 0, 1, 1]"
17,logo_316_animation_5,4,1,0.2,1.00,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.6229016948897...","[4, 6, 24, 23]","[1, 2, 6, 7]","[0, 1, 1, 0, 0, 0, 1, 1]"
18,logo_316_animation_5,6,2,0.6,1.25,"[0, 0, 1, 0, 0, 0, -1.0, -1.0, -1.0, 0.7417869...","[4, 6, 24, 23]","[1, 2, 6, 7]","[0, 1, 1, 0, 0, 0, 1, 1]"
19,logo_316_animation_5,24,6,0.2,1.50,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.7951935655656...","[4, 6, 24, 23]","[1, 2, 6, 7]","[0, 1, 1, 0, 0, 0, 1, 1]"

In [6]:
# save dataframe
output = open(f"data/surrogate_model/animation_vectors.pkl", 'wb')
pickle.dump(df_combined, output)
output.close()

### 3. Create backend mapping

In [19]:
backend_mapping_df = create_backend_mapping_df(df_combined)
backend_mapping_df

                   file  0  1  2  3  4  5  6  7
0    logo_0_animation_0  1  1  0  1  1  1  0  1
1    logo_0_animation_1  0  1  0  0  0  0  0  0
2    logo_0_animation_2  0  0  1  1  0  1  0  1
3    logo_0_animation_3  1  0  1  1  0  0  0  0
4   logo_72_animation_0  1  1  1  1  1  0  1  1
5   logo_72_animation_1  1  1  1  1  1  0  1  1
6   logo_72_animation_2  1  1  1  1  1  0  1  1
7   logo_72_animation_3  1  1  1  1  0  0  0  1
8   logo_73_animation_0  1  1  1  1  1  1  1  0
9   logo_73_animation_1  1  1  1  1  1  1  1  0
10  logo_73_animation_2  1  1  1  1  1  1  1  0
11  logo_73_animation_3  1  1  1  1  0  1  1  0

In [21]:
# save backend mapping
backend_mapping_df.to_csv('data/animated_svgs_dataframes/backend_mapping.csv', index=False)

### 4. Insert label in concatenated dataframe
To-do: Insert label as new column in the following dataframe.

In [85]:
label = pd.read_csv("data/label_animation_path/export_table_animation_path_label_9.4.2021.csv", skiprows=[1],
                                        dtype={"alias": object, "animation_file": object, "animation_id": int,
                                               "logo_id": int, "path_0_rating": object, "path_1_rating": object,
                                               "path_2_rating": object, "path_3_rating": object, 
                                               "path_4_rating": object, "path_5_rating": object, 
                                               "path_6_rating": object, "path_7_rating": object,
                                               "time": object})

In [86]:
label_melt = pd.melt(label, id_vars=["alias","animation_file", "animation_id", "logo_id", "time"],
                                  value_vars=["path_0_rating", "path_1_rating", "path_2_rating", "path_3_rating",
                                              "path_4_rating", "path_5_rating", "path_6_rating", "path_7_rating"],
                                  var_name="path", value_name="label").assign(order_id=label_melt.path.str.extract("(\d+)")).astype({"order_id": 'int'})

In [87]:
label_melt_id = label_melt.assign(order_id=label_melt.path.str.extract("(\d+)")).astype({"order_id": 'int'}).rename(columns={"animation_id":"animation_number"}).drop("path",1)

In [93]:
label_melt_id[label_melt_id.logo_id == 376][label_melt_id.animation_number == 0]

,alias,animation_file,animation_number,logo_id,time,label,order_id
2078,Tim,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617778857, nanoseconds=3400...",no_rating,0
2653,Jakob,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617885269, nanoseconds=3560...",Good,0
4963,Tim,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617778857, nanoseconds=3400...",no_rating,1
5538,Jakob,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617885269, nanoseconds=3560...",no_rating,1
7848,Tim,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617778857, nanoseconds=3400...",no_rating,2
...,...,...,...,...,...,...,...
17078,Jakob,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617885269, nanoseconds=3560...",no_rating,5
19388,Tim,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617778857, nanoseconds=3400...",no_rating,6
19963,Jakob,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617885269, nanoseconds=3560...",no_rating,6
22273,Tim,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617778857, nanoseconds=3400...",no_rating,7
22848,Jakob,animation/logo_376_animation_0.svg,0,376,"Timestamp(seconds=1617885269, nanoseconds=3560...",no_rating,7

In [89]:
df_combined_id = df_combined.assign(
    logo_id=df_combined.file.str.extract("logo_(\d+)"),
    animation_number=df_combined.file.str.extract("animation_(\d+)")).astype({"logo_id": 'int',"animation_number": 'int'})

In [90]:
df_combined_id

,file,animation_id,order_id,path_prob,begin_value,model_output,animated_animation_ids,animated_order_ids,backend_mapping,logo_id,animation_number
0,logo_316_animation_0,4,1,0.200000,1.00,"[0, 0, 0, 1, 0, 0, -1.0, -1.0, -1.0, -1.0, 0.8...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,0
1,logo_316_animation_0,24,6,0.600000,1.25,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,0
2,logo_316_animation_0,23,7,0.200000,1.50,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,0
3,logo_316_animation_1,4,1,0.200000,1.00,"[1, 0, 0, 0, 0, 0, 0.13436424411240122, 0.8474...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,1
4,logo_316_animation_1,24,6,0.600000,1.25,"[0, 0, 1, 0, 0, 0, -1.0, -1.0, -1.0, 0.7637746...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,1
...,...,...,...,...,...,...,...,...,...,...,...
23653,logo_91_animation_22,22,1,0.916667,1.00,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,22
23654,logo_91_animation_23,21,0,0.916667,1.25,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,23
23655,logo_91_animation_23,22,1,0.916667,1.00,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.9248652516259...","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,23
23656,logo_91_animation_24,21,0,0.916667,1.25,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,24
23657,logo_91_animation_24,22,1,0.916667,1.00,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.7123429878269...","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,24

In [95]:
# Combine dataframes and merge data
label_path_merged = pd.merge(df_combined_id, label_melt_id, how='left', on=["logo_id","animation_number","order_id"])

In [96]:
label_path_merged

,file,animation_id,order_id,path_prob,begin_value,model_output,animated_animation_ids,animated_order_ids,backend_mapping,logo_id,animation_number,alias,animation_file,time,label
0,logo_316_animation_0,4,1,0.200000,1.00,"[0, 0, 0, 1, 0, 0, -1.0, -1.0, -1.0, -1.0, 0.8...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,0,Jakob,animation/logo_316_animation_0.svg,"Timestamp(seconds=1617783014, nanoseconds=3260...",Good
1,logo_316_animation_0,24,6,0.600000,1.25,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,0,Jakob,animation/logo_316_animation_0.svg,"Timestamp(seconds=1617783014, nanoseconds=3260...",Good
2,logo_316_animation_0,23,7,0.200000,1.50,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,0,Jakob,animation/logo_316_animation_0.svg,"Timestamp(seconds=1617783014, nanoseconds=3260...",Good
3,logo_316_animation_1,4,1,0.200000,1.00,"[1, 0, 0, 0, 0, 0, 0.13436424411240122, 0.8474...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,1,Jonathan,animation/logo_316_animation_1.svg,"Timestamp(seconds=1617813571, nanoseconds=9700...",Very Bad
4,logo_316_animation_1,24,6,0.600000,1.25,"[0, 0, 1, 0, 0, 0, -1.0, -1.0, -1.0, 0.7637746...","[4, 24, 23]","[1, 6, 7]","[0, 1, 0, 0, 0, 0, 1, 1]",316,1,Jonathan,animation/logo_316_animation_1.svg,"Timestamp(seconds=1617813571, nanoseconds=9700...",Okay
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23714,logo_91_animation_22,22,1,0.916667,1.00,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,22,NaN,NaN,NaN,NaN
23715,logo_91_animation_23,21,0,0.916667,1.25,"[0, 0, 0, 0, 0, 1, -1.0, -1.0, -1.0, -1.0, -1....","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,23,NaN,NaN,NaN,NaN
23716,logo_91_animation_23,22,1,0.916667,1.00,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.9248652516259...","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,23,NaN,NaN,NaN,NaN
23717,logo_91_animation_24,21,0,0.916667,1.25,"[0, 0, 0, 0, 1, 0, -1.0, -1.0, -1.0, -1.0, -1....","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,24,NaN,NaN,NaN,NaN
23718,logo_91_animation_24,22,1,0.916667,1.00,"[0, 1, 0, 0, 0, 0, -1.0, -1.0, 0.7123429878269...","[21, 22]","[0, 1]","[1, 1, 0, 0, 0, 0, 0, 0]",91,24,NaN,NaN,NaN,NaN

In [97]:
# save dataframe
output = open(f"data/surrogate_model/animation_label.pkl", 'wb')
pickle.dump(label_path_merged, output)
output.close()