In [1]:
import os
os.chdir("..")
from src.preprocessing.transform_into_model_data_ff import *
import pickle
import pandas as pd

### Load training and test data

In [2]:
with open('data/animation_label/surrogate_model_train.pkl', 'rb') as f:
    sm_train = pickle.load(f)
    
with open('data/animation_label/surrogate_model_test.pkl', 'rb') as f:
    sm_test = pickle.load(f)

### Encode ratings

In [3]:
sm_train.head()

,rating,file,logo,0_x,1_x,2_x,3_x,4_x,5_x,6_x,...,emb_22,emb_23,emb_24,emb_25,emb_26,emb_27,emb_28,emb_29,emb_30,emb_31
0,1.0,logo_0_animation_0,logo_0,0.0,0.0,0.0,0.0,1.0,0.0,0.844422,...,-0.233472,0.151296,-0.273250,0.005558,-1.396540,-0.691423,-0.463657,1.063568,-0.531747,-0.125945
1,1.0,logo_0_animation_1,logo_0,0.0,0.0,0.0,0.0,0.0,0.0,-1.000000,...,-0.233458,0.151287,-0.273240,0.005559,-1.396550,-0.691419,-0.463666,1.063567,-0.531751,-0.125942
2,3.0,logo_0_animation_2,logo_0,0.0,0.0,0.0,0.0,0.0,0.0,-1.000000,...,-0.233473,0.151303,-0.273241,0.005558,-1.396537,-0.691423,-0.463662,1.063561,-0.531750,-0.125936
3,0.0,logo_0_animation_3,logo_0,0.0,0.0,0.0,0.0,1.0,0.0,0.237965,...,-0.233462,0.151294,-0.273250,0.005565,-1.396538,-0.691428,-0.463663,1.063564,-0.531744,-0.125942
4,1.0,logo_0_animation_4,logo_0,0.0,0.0,0.0,1.0,0.0,0.0,0.236048,...,-0.233454,0.151289,-0.273249,0.005551,-1.396529,-0.691423,-0.463668,1.063562,-0.531749,-0.125946

In [4]:
ratings_train = np.array(sm_train["rating"])
ratings_test = np.array(sm_test["rating"])

In [5]:
ratings_train = pd.DataFrame(encode_classes(ratings_train.reshape(-1,1)), columns=['rating_0','rating_1','rating_2','rating_3'])
ratings_test = pd.DataFrame(encode_classes(ratings_test.reshape(-1,1)), columns=['rating_0','rating_1','rating_2','rating_3'])

In [6]:
sm_train = pd.concat([sm_train, ratings_train], axis=1)
sm_test = pd.concat([sm_test, ratings_test], axis=1)

### Drop unnecessary columns

In [7]:
sm_train.drop(['rating', 'file', 'logo'], axis=1, inplace=True)
sm_test.drop(['rating', 'file', 'logo'], axis=1, inplace=True)

In [8]:
sm_train.head()

,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,...,emb_26,emb_27,emb_28,emb_29,emb_30,emb_31,rating_0,rating_1,rating_2,rating_3
0,0.0,0.0,0.0,0.0,1.0,0.0,0.844422,0.757954,0.420572,0.258917,...,-1.396540,-0.691423,-0.463657,1.063568,-0.531747,-0.125945,1,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.396550,-0.691419,-0.463666,1.063567,-0.531751,-0.125942,1,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.396537,-0.691423,-0.463662,1.063561,-0.531750,-0.125936,1,1,1,0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.237965,0.544229,0.369955,0.603920,...,-1.396538,-0.691428,-0.463663,1.063564,-0.531744,-0.125942,0,0,0,0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.236048,0.103166,0.396058,0.154972,...,-1.396529,-0.691423,-0.463668,1.063562,-0.531749,-0.125946,1,0,0,0

In [9]:
sm_test.head()

,0_x,1_x,2_x,3_x,4_x,5_x,6_x,7_x,8_x,9_x,...,emb_26,emb_27,emb_28,emb_29,emb_30,emb_31,rating_0,rating_1,rating_2,rating_3
0,0.0,0.0,0.0,0.0,1.0,0.0,0.844422,0.757954,0.420572,0.258917,...,-0.248943,-0.456305,0.366836,-0.27765,0.051369,0.69193,0,0,0,0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.134364,0.847434,0.763775,0.255069,...,-0.248943,-0.456305,0.366836,-0.27765,0.051369,0.69193,1,0,0,0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.956034,0.947827,0.056551,0.084872,...,-0.248943,-0.456305,0.366836,-0.27765,0.051369,0.69193,1,0,0,0
3,0.0,0.0,0.0,0.0,1.0,0.0,0.237965,0.544229,0.369955,0.603920,...,-0.248943,-0.456305,0.366836,-0.27765,0.051369,0.69193,1,1,1,0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.236048,0.103166,0.396058,0.154972,...,-0.248943,-0.456305,0.366836,-0.27765,0.051369,0.69193,1,0,0,0

### Save data

In [10]:
sm_train.to_csv('data/fitness_function/train_ff.csv', index=False)
sm_test.to_csv('data/fitness_function/test_ff.csv', index=False)